[env:waveshare_esp32s3_eink]
platform = espressif32
board = waveshare_esp32s3_epaper_154g
framework = arduino
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1

    -I include

build_src_filter =
    +<*>
    +<../include/src/>

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit EPD
    bblanchon/ArduinoJson @ ^7
    GxEPD2@^1.4.10
